default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: sevendays_api_development

  host: localhost
  port: 5432
  username: sevendays_api
  password: postgres

test:
  <<: *default
  database: sevendays_api_test

production:
  primary: &primary_production
    <<: *default
    database: sevendays_api_production
    username: sevendays_api
    password: <%= ENV["SEVENDAYS_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: sevendays_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sevendays_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sevendays_api_production_cable
    migrations_paths: db/cable_migrate
